const data = {
    design: [
        {
            title: "My Wordmark",
            cover: "../img/wordmark-grey.jpg",
            cover_color: "../img/wordmark-color.jpg",
            src1: "../img/wordmark-initial.jpg",
            src2: "../img/wordmark-testing.jpg",
            src3: "../img/wordmark-final.jpg",
            src4: "../img/wordmark-variations.jpg",
            slide1: "The Start",
            slide2: "Refining",
            slide3: "The Final",
            slide4: "Variations",
            info1: "A Few Sketches. I've Never Really Been Sure What I Like For My Own Personal Logo. I Wanted To Include My Initials.",
            info2: "Everytime I've Made A Personal Logo, I've Gotten Bored Of It, So I Wanted Something That I Would Be Happy With, And Be Classic.",
            info3: "A JTL Surrounded With A Roundel. Looks Great In Any Size, Black & White Or Color, And Really Showcases What I Can Do.",
            info4: "Seeing How The Logo Can Be Used In Different Mediums, And Styles. I'm Incredibly Happy With How It Turned Out.",
        },
        {
            title: "Michigan Machine",
            cover: "../img/machine-grey.jpg",
            cover_color: "../img/machine-color.jpg",
            src1: "../img/machine-final.jpg",
            src2: "../img/machine-promo.jpg",
            src3: "../img/machine-social.jpg",
            src4: "../img/machine-store.jpg",
            slide1: "The Logo",
            slide2: "Promos",
            slide3: "Social Media",
            slide4: "The Shop",
            info1: "A Logo Designed For The Automotive History Of Michigan. A Wrench Can Be Seen In The Negative Space.",
            info2: "A Promo Featuring The Captain Of The Machine, Showcasing The Night's Game Between Them And Another NHL Rival.",
            info3: "A Social Media Graphic Showcasing The Game Score For The Night. Can Be Templated And Re-used.",
            info4: "A Promotional Showing Off Machine Gear, As Well As Season Tickets, A High-Value Item For Hockey Teams, With Free Hat.",
        },
        {
            title: "Dazzling Data Merch",
            cover: "../img/eds-grey.jpg",
            cover_color: "../img/eds-color.jpg",
            src1: "../img/eds-1.jpg",
            src2: "../img/eds-2.jpg",
            src3: "../img/eds-3.jpg",
            src4: "../img/eds-final.jpg",
            slide1: "Styles 1 & 2",
            slide2: "Styles 3 & 4",
            slide3: "Styles 5 & 6",
            slide4: "Printed Merch",
            info1: "Collaboration With The Data Science Ethics Group fullyConnected, Which Aims To Make Sure AI Is Used Ethically.",
            info2: "Mostly Based Off Of Other Familiar Brands, i.e. Black Panther, SuperHot Video Game, D.R.E.A.M. And More.",
            info3: "These Were Done In Collaboration To Be Used For A Variety Of Products.",
            info4: "Some Of The Final Products. They Will Be Live And Ready For Sale Soon.",
        },
        {
            title: "Makeup Ad",
            cover: "../img/makeup-grey.jpg",
            cover_color: "../img/makeup-color.jpg",
            src1: "../img/makeup1.jpg",
            src2: "../img/makeup2.jpg",
            src3: "../img/makeup3.jpg",
            src4: "../img/makeup4.jpg",
            slide1: "SoSi Logo",
            slide2: "1st Ad",
            slide3: "2nd Ad",
            slide4: "Magazine Mockup",
            info1: "First The Logo; Simple, Classic, Elegant, But Different To Stand Out And Be Instantly Recognizable.",
            info2: "Ad Showcasing A New Product, Saturn, Associating Style With The Stars And Astrological Signs.",
            info3: "Ad Showcasing Jupiter, The Second In The SoSi Astrological Signs",
            info4: "WHat It Would Look Like If SoSi Took Out A Full Page Ad In A Magazine. Subtle, Yet Strong.",
        },
        {
            title: "Logos 1",
            cover: "../img/logos-grey.jpg",
            cover_color: "../img/logos-color.jpg",
            src1: "../img/logos1.jpg",
            src2: "../img/logos2.jpg",
            src3: "../img/logos3.jpg",
            src4: "../img/logos4.jpg",
            slide1: "Throttle Energy Drink",
            slide2: "Austin Water Co",
            slide3: "Cover Music App",
            slide4: "Neversquare Bank",
            info1: "An Energy Drink That Prompts One To Fuel Their Life, Complete With Package Designs. ",
            info2: "A Logo For THe City Of Austin's Water Company. Simple, Yet Classy.",
            info3: "A Logo For An App Where Users Upload Covers Of Well Known Songs, a la Johnny Cash's Hurt.",
            info4: "A Logo For A Bank's Local Payment App.",
        },
        {
            title: "Logos 2",
            cover: "../img/logos2-grey.jpg",
            cover_color: "../img/logos2-color.jpg",
            src1: "../img/logos5.jpg",
            src2: "../img/logos6.jpg",
            src3: "../img/logos7.jpg",
            src4: "../img/logos8.jpg",
            slide1: "Regale Co",
            slide2: "Express Texting App",
            slide3: "Ego Company",
            slide4: "Broken Carousel",
            info1: "A Simple, Elegant Logo For A Black Woman-Run Company.",
            info2: "An Anonymous Texting App Where Users Can Express Themselves",
            info3: "A Corperate Logo Based In Identity Metrics.",
            info4: "An Illustration Of A Carousel Horse Breaking Free. Meant To Inspire And Show Breaking The Chains.",
        },
        {
            title: "Logos 3",
            cover: "../img/logos3-grey.jpg",
            cover_color: "../img/logos3-color.jpg",
            src1: "../img/logos9.jpg",
            src2: "../img/logos10.jpg",
            src3: "../img/logos11.jpg",
            src4: "../img/logos12.jpg",
            slide1: "Washington Freedom Hockey",
            slide2: "Houston Apollos Minor League",
            slide3: "Apollos Launch Pad Shop",
            slide4: "West Kings Customs",
            info1: "A Minor League Hockey Team Based In Washington D.C. Based Off The Colors Of The USA Flag.",
            info2: "An AA Minor League Baseball Team. Wanted To Experiment With A Unique Color",
            info3: "The Launchpad, A Splash Graphic For The Apollos Team Shop. Experimenting To See If Colors Could Work.",
            info4: "A Custom Car Painting Group Based In California, a la West Coast Customs.",
        },
        {
            title: "Logos 4",
            cover: "../img/logos4-grey.jpg",
            cover_color: "../img/logos4-color.jpg",
            src1: "../img/logos13.jpg",
            src2: "../img/logos14.jpg",
            src3: "../img/logos15.jpg",
            src4: "../img/logos16.jpg",
            slide1: "Steel | Line",
            slide2: "Grand Rapids Logo",
            slide3: "Carolina Hurricanes Logo Rework",
            slide4: "Hidden Forest Wine",
            info1: "A Logo For An E-Commerce Store That Specializes In Pittsburgh Sports.",
            info2: "A Wordmark For A Grand Rapids Sports Team.",
            info3: "A Reworking Of The Carolina Hurricane's Logo Of The National Hockey League.",
            info4: "A Wine Brand, With The Backstory Of A Vineyard Being Discovered In The Forest. ",
        },
        {
            title: "Exercise Graphics",
            cover: "../img/exercise-grey.jpg",
            cover_color: "../img/exercise-color.jpg",
            src1: "../img/exercise1.jpg",
            src2: "../img/exercise2.jpg",
            src3: "../img/exercise3.jpg",
            src4: "../img/exercise4.jpg",
            slide1: "No More Excuses",
            slide2: "Sunset Run",
            slide3: "Going Going Gone",
            slide4: "Light Catch Burn",
            info1: "A Set Of Graphics Designed For K&S FITS, An Exercise Apparel Company.",
            info2: "A Set Of Graphics Designed For K&S FITS, An Exercise Apparel Company.",
            info3: "A Set Of Graphics Designed For K&S FITS, An Exercise Apparel Company.",
            info4: "A Set Of Graphics Designed For K&S FITS, An Exercise Apparel Company.",
        },
        {
            title: "Illustrations",
            cover: "../img/illust-grey.jpg",
            cover_color: "../img/illust-color.jpg",
            src1: "../img/illust1.jpg",
            src2: "../img/illust2.jpg",
            src3: "../img/illust3.jpg",
            src4: "../img/illust4.jpg",
            slide1: "Let The Pain Build You, Teach You",
            slide2: "O To Dance In The Light Of Things Long Dead",
            slide3: "The ABCs Of The NHL",
            slide4: "Black And Yellow",
            info1: "An Animal Skull In A Roundel With A Nihilistic Phrase, Done In A Yellow Cloud.",
            info2: "Two Silhouettes Dancing In The Lights Of Stars.",
            info3: "A Children's Style Collection Featuring The National Hockey League, Two Of A Larger Set.",
            info4: "Illustrated Designs Of Pittsburgh's Greatest Sports Heroes, Sidney Crosby, Roberto Clemente, And Troy Palumalu.",
        },
        {
            title: "Trading Cards",
            cover: "../img/cards-grey.jpg",
            cover_color: "../img/cards-color.jpg",
            src1: "../img/cards1.jpg",
            src2: "../img/cards2.jpg",
            src3: "../img/cards3.jpg",
            src4: "../img/cards4.jpg",
            slide1: "Grungy, but clean",
            slide2: "Clean Photography",
            slide3: "Striking And Bold",
            slide4: "Colorful, but Bright.",
            info1: "An Autograph Card Featuring Henrik Zetterberg, And Three Previous Captains Who Won The Stanley Cup.",
            info2: "A Metallic See-Through Autograph of Joe Sakic, And A Base Card Focusing On Photography.",
            info3: "A Colorful Autograph Focusing On Retro Players, And A Bold Black And White Themed Autograph.",
            info4: "A Set Of Autographs Featuring Key Players Of The National Women's Hockey League.",
        },
        {
            title: "Phone Wallpapers",
            cover: "../img/wallpaper-grey.jpg",
            cover_color: "../img/wallpaper-color.jpg",
            src1: "../img/wallpaper1.jpg",
            src2: "../img/wallpaper2.jpg",
            src3: "../img/wallpaper3.jpg",
            src4: "../img/wallpaper4.jpg",
            slide1: "NWHL 2021 Isobel Cup",
            slide2: "Marc-Andre Fleury Vegas",
            slide3: "Alex Ovechkin Washington",
            slide4: "Cale Makar Colorado Character Select",
            info1: "Four Wallpapers Based On The Original 4 Teams In The National Women's Hockey League.",
            info2: "Stylized Illustration Of Vegas Golden Knights Goaltender Marc-Andre Fleury.",
            info3: "Blue And Red Graphics Featuring Washington Capitals Captain Alexander Ovechkin.",
            info4: "Defenseman Cale Makar Of The Colorado Avalanche In The Style Of The TMNT Character Select Screen.",
        },
    ],
    code: [
        {
            title: "Steel | Line",
            cover: "../img/steelline-grey.jpg",
            cover_color: "../img/steelline.jpg",
            header: "../img/steelline-cover-full.jpg",
            link: "http://steelline-app.herokuapp.com/",
            overview: "I wanted to create an e-commerce site, completely functional, with a way to create products, sell and ship, search by several parameters, add to and remove from cart, create users and admins, launch on heroku, utilize Mongo DB, Postman, and more. This was my first project in React.",
            work: "I went through several tutorials to learn how to use React, first. Then I built the basic page, the created each item which included all the data for it, and several photos for each, then uploaded to Mongo DB. I made it so you could search by several parameters(Team, brand, jersey/hat/shirt/etc). After, I made it so users could sign up and create an account, as well as make admin accounts that have more options. Then I made a cart so users could find a product, click on the info, and add a quantity to their cart. Then I made it so they could check out, and include their shipping address and PayPal information. Then the seller or admin could confirm shipping and delivery. I also gave the admin the ability to upload a product directly from their computer instead of having to upload it directly to MongoDB, as well as edit users. Added an order history screen for each user, followed by pagination for searches that result in many products returning, and a filter option, so a user can filter their results. Finally, I added the small details, i.e. free shipping for carts over $100, Sold Out and Almost Sold Out signage for low quantity items, and added reviews, so users could rate and review the products.",
            learned: "So much. This was my most ambitious project yet, and it took a lot of planning to do it right. I learned React pretty hands on, diving right in, experiencing a better search system, and how to make a one-page site using React-router-dom. I also learned some back end for the first time, finagling with Mongo DB, Postman, and Heroku. It was all very new to me, so several mistakes were made, but I got through them all. Also figured out how to make it so users and admin would be created using Mongo.",
            howHappy: "Pretty happy with this. This was my first foray into React and it was genuinely a lot of fun. As usual, I was too ambitious, and the project went far longer than I had anticipated, but I still was able to add everything I wanted. Plus it looks sharp.",
            problems: "Several. At one point the entire folder was wiped, so I had to start completely over about halfway through, losing about 100 hours of work. Plus learning the ins and outs of React were an adventure. Also, learning how to use Mongo DB and seed products and users was fun. I had a few problems learning how to consistantly connect my site with mongo and Heroku, but I was able to and now it runs great.",
        },
        {
            title: "Bookbound",
            cover: "../img/bookbound-grey.jpg",
            cover_color: "../img/bookbound.jpg",
            header: "../img/bookbound-cover-full.jpg",
            link: "https://jtlovato.github.io/bookbound/",
            overview: "I wanted to create a simple, great looking one-page site for book lovers, that incorperated a book club and gave users a way to find others.",
            work: "One of my problems I recognize is that I get overly ambitious and plan to give a site a million different features. With Bookbound, I wanted to just keep it simple.As a result, it's a one page site that has a carousel, google maps api for locating libraries, and overall had a very down-home very local look to it. ",
            learned: "I wanted to still have a few neat little features, and learned how to create a rudimentary chat box, so anyone on the site could chat about the book of the month. I also made a custom Google Map API that showed a library in each state. I also added a calender that showed the day of the next meeting(which is always two weeks from the current date).",
            howHappy: "Pretty happy. I really wanted to focus on the design of the site, that looked good on mobile and desktop. It is a little simple but I feel for a small-town's book club it does it's purpose.",
            problems: "Figuring out how to connect the Google Maps API tripped me up for a minute, as well as the chat box. But everything else outside that was pretty straight forward. ",
        },
        {
            title: "Zero-G Bar",
            cover: "../img/zerogbar-grey.jpg",
            cover_color: "../img/zerogbar.jpg",
            header: "../img/zerogbar-cover-full.jpg",
            link: "https://jtlovato.github.io/ZeroGBar/",
            overview: "A site for a galaxy-themed bar, simple but had just what you needed for a bar; drinks, menus, and live music. This site was me focusing more on mobile view ports, while also attempting to \"tone down\" how much I do in code. At this point I was still learning and found myself making the code much more complicated than it needed to be. This was a project I made during my time at Treehouse Bootcamp.",
            work: "Expanding my knowledge on Javascript, even just to apply it to simple sites. Used CSS to really make sure it looked good on several viewports, as well as experimenting with how .pngs would appear and how they could be used to create a dynamic design that isn't all blocks. Added simple (at the time very difficult) features such as a countdown for the grand opening of a second bar, a menu modal, and small reviews carousel.",
            learned: "Playing around with the simpler features of Javascript, as well as getting a better handle on CSS, and experimenting with the see-through .png filename.",
            howHappy: "Mostly yes. I feel it lacks the refinement of a site made by someone who has years of experience, but overall I am happy with it. The header looks great and the \"Ripped Space\" design creates an interesting background.",
            problems: "FIxing everything so it would look nice, regardless of viewport. Also nailing down some of the finer points of CSS positioning. ",
        },
        {
            title: "The Goalie Mask Project",
            cover: "../img/tgmp-grey.jpg",
            cover_color: "../img/tgmp.jpg",
            header: "../img/tgmp-cover-full.jpg",
            link: "https://jtlovato.github.io/GoalieMaskProject.com/",
            overview: "A bit of a pet project of mine. I wanted to showcase the history of goalie masks through hockey history, which would include each current teams goalie tandem's masks, an ability to search by team or player, as well as a blog and news from around the National Hockey League. This was a project I made during my time at Treehouse Bootcamp.",
            work: "One of my first completed sites. I wanted to show each mask in the NHL currently, as well as famous masks from NHL history. I made it so you could search by player or team. Whe you go into the team search, it pulls up a modal that shows both goalies from each team in a graphic slider, that transitions from each side to show off each goalie's mask. I also added a simple blog, news, and made it so the front page brings up a random mask, and a player of the day.",
            learned: "Still very much experimenting with Javascript, as well as getting CSS down. This was when I really learned what Javascript can do; when a user takes the slider on the modal and moves it back and forth, it exposes different parts of two pictures, creating a dynamic, engaging, and colorful product.",
            howHappy: "Looking back on it now, not very. I very much want to redo this in React and reallty make it shine. I was hesitant to show this one but I wanted to show off how far I've come. There are a several viewport issues plaguing the site, and it looks like it somehow has gotten worse with time. The design overall I'm pretty happy with, ice-white with pops of color, but I feel redoing this in React wouldn't take as long as it did in sinmple JS.",
            problems: "Just learning more Javascript and realizing how much testing is needed after, and how much planning is needed before, to really make one cohesive site that works well and flows better. This is a bit of a UX/UI learning experience.",
        },
        {
            title: "Cover",
            cover: "../img/cover-grey.jpg",
            cover_color: "../img/cover.jpg",
            header: "../img/cover-cover-full.jpg",
            link: "https://jtlovato.github.io/CoverApp/",
            overview: "I love covers of songs, it's an amazing of hearing some of your favorite songs in an entire different light. From \"Blue Eyes\" to \"Hurt\", I wanted to create a site that focuses specifically on covers, done with entirely new instruments, in entirely different genres. This was a project I made during my time at Treehouse Bootcamp.",
            work: "Still learning CSS and Javascript, I wanted to be able to have users have a profile, listen to and upload self-made covers of their favorite songs, complete with a little overlayed modal as a record player, not unlike Spotify. I also wanted them to find new music suggested for them, based off a random user generator API.",
            learned: "I was focusing on expanding my Javascript knowledge, including pulling from an outside API, which I used to create the \"New For You\" section. I also learned how to upload media and expanded my knowledge on fundamental CSS and HTML tags. I also challenged myself to see if I could create a Light Mode, that would change the darker colors into a brighter experience.",
            howHappy: "Right now, not very. My amateurishness was absolutely showing through, and I'd love to remake this one, but so users can actually upload their own music, as well as style it a lot better. I didn't realize how bare-bones it felt at the time. ",
            problems: "It's incredibly simple, and with almost no features. The positioning isn't great, and while I like the idea of the orange white and black color scheme, it didn't translate well here. The API also doesn't pull consistantly. I'd really like to remake this one soon.",
        },
        {
            title: "Honee",
            cover: "../img/honee-grey.jpg",
            cover_color: "../img/honee.jpg",
            header: "../img/honee-cover-full.jpg",
            link: "https://jtlovato.github.io/Honee/",
            overview: "I wanted to make a site that would help BiPOC. During 2020 I saw a lot of injustice happening, and a lot of people asking how they could help, before quickly giving up and moving on with their lives. I wanted to make a difference, even a small one, and create a site that helps BiPOC connect with one another and discuss the world, and the state of their physical and mental health.",
            work: "Still learning Javascript, I started small and eventually added too many pieces I hadn't planned for. I initially started with the simple hexagon on the left, that would record how many days in a row a person has tried to help their health. I eventually added a little community section on the right hand side that would bring people together. This was a project I made during my time at Treehouse Bootcamp.",
            learned: "I really was experimenting with SVGs and how they work, and unfortunately it did not produce the desired effect. I also was working on local storage memory so it could keep track of a user's history and how many days in a row they succeeded in taking care of themselves.",
            howHappy: "Not very. The positioning is off, on several viewports, animations are not great, and there are a ton of problems. I didn't plan it out at all and that was a learning experience. The good intent was there, but the execution was not.",
            problems: "I had several problems with this, mostly from learning CSS positioning, but I also didn't realize at the time I needed to check several viewports to see how a site does on them, as well as browsers. The actual Javascript seems fine, if not very simple, but the majority of the problems come from a lack of planning, and knowledge on positioning SVGs.",
        },              
    ],

    blogs: [
        {
            _id: '1',
            title: "Everything Wrong With Amazon",
            subTitle: "What Is Going On In Amazon's Headquarters?",
            date: "March 16th 2021",
            card: "../img/blog/amazon-button.jpg",
            src: "../img/blog/amazon-header.jpg",
            text: "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?, But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?, But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?",
            tags: ["butts, ","ass, "],
        },
        {
            _id: '2',
            title: "Dr Feelgood, Or; How I learned to stop worrying And Love The Bomb",
            subTitle: "more stuff",
            date: "noooow",
            card: "../img/blog/amazon-button.jpg",
            src: "../img/blog/amazon-header.jpg",
            text: "gdfgfdsg",
            tags: ["butts","ass"],
        },
        {
            _id: '3',
            title: "Base Title",
            subTitle: "Things About It Go Here",
            date: "March 16th 2021",
            cardSrc: "",
            src: "",
            text: "SO MUCH LOREM IPSOM",
            tags: ["butts","ass"],
        },
        {
            _id: '4',
            title: "stuff",
            subTitle: "more stuff",
            date: "noooow",
            cardSrc: "www",
            src: "fsdf",
            text: "gdfgfdsg",
            tags: ["butts","ass"],
        },
    ],
};

export default data;